### ISSUE TITLE
My MP1 Topic

### ISSUE THREAD

**Issue by kare-ren** [mdeleon7/MiniProject1#1]
My idea (if all goes well) is to use recipes for my analysis. If I run into problems, I also like the idea of comparing books, like the example, since I enjoy reading!

**Comment by mdeleon7** [comment]
I think that's a good idea. I'm interested to see what you can do with a data set of recipes.

**Comment by kare-ren** [comment]
My results can be found here for any further discussion! https://github.com/kare-ren/MiniProject1/blob/master/klee50.ipynb
